line-length = 88

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes  
    "I",   # isort
    "C90",
]

[lint.per-file-ignores]
"**/migrations/*.py" = ["E501", "I001"]
"**/settings.py" = ["E501"]